spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: ${APP_JWT_SECRET}
  expiration: 3600
  refreshExpiration: 86400
newsApi:
  url: ${NEWS_API_URL}
  key: ${NEWS_API_KEY}
huggingface:
  api:
    key: ${HUGGINGFACE_API_KEY}


